age = int(input("Сколько тебе лет?"))
print("Через год тебе будет", age + 1)
print("Через 5 лет тебе будет", age + 5)
print("Через 10 лет тебе будет", age + 10)
print("Через 20 лет тебе будет", age + 20)
# height = int(input("Какой у тебя рост?"))
# print("Твой рост", height)
# weight = int(input("Какой у тебя вес?"))
# print("Твой вес", weight)
