# name = input("Как тебя зовут? ")
# print(type(name))
# print(len(name))
# print(name.upper())
# print(name.lower())
# print(name.replace("Де", "До"))
# city = input("Из какого ты города? ")
# print(type(city))
# print(len(city))
# print(city.upper())
# print(city.lower())
# print(city.capitalize())
# print(city.replace("Усть-Илимск", "Петровск-Забайкальский"))
height = int(input("Какой у тебя рост?" ))
print(type(height))
